### ISSUE TITLE
jQuery validation conflict?

### ISSUE THREAD

**Issue by Aurora7Sys** [TimothyMeadows/reCAPTCHA.AspNetCore#17] opened 2019-04-11 18:17 UTC
Thanks again @TimothyMeadows for all of your work on this! It looks like we may have a new problem.

- With 2.2.1 and 2.2.2 all is well with the included test application here using both "v2" and "v2-invis".
- If I uses a .net core 2.2 app with Razor Pages  /  "v2" and "v2-invis" and copy and paste your fom form the test app here, everything works fine.
- If I uses a .net core 2.2 app with Razor Pages  /  "v2" and a form that uses jQuery validaton / tag helpers everything is fine.
- If I uses a .net core 2.2 app with Razor Pages  /  "v2-invis" and a form that uses jQuery validaton / tag helpers everything NOT fine. 
- I didn't try this on the MVC app.

In one app the jQuery validation doesn't work at all and on another app it seems the form doesn't get posted at all and there are errors on the console saying that recaptcha has already been rendered 

recaptcha__en.js:519 Uncaught Error: reCAPTCHA has already been rendered in this element
    at Object.Fd (recaptcha__en.js:519)
    at _5a5ca599_9550_4e83_b887_d45f8c348a10 (contact:185)
    at $p (recaptcha__en.js:507)
    at iG (recaptcha__en.js:508)
    at recaptcha__en.js:521
    at recaptcha__en.js:540
AAuE7mDuI1pqB7h1LyRUm04SML-HpWIjXkqEuv0worO3aw:1 Failed to load resource: the server responded with a status of 404 ()
AAuE7mDuI1pqB7h1LyRUm04SML-HpWIjXkqEuv0worO3aw:1 Failed to load resource: the server responded with a status of 404 ()
AAuE7mDuI1pqB7h1LyRUm04SML-HpWIjXkqEuv0worO3aw:1 Failed to load resource: the server responded with a status of 404 ()

**Comment by Aurora7Sys** [comment] 2019-04-11 18:22
I am looking in to the situation more with the more complex, second scenario to make sure that app isn't just doing something strange. The first scenario is with a very simple, bare bones Razor Pages test app. There are no errors on the console there but validation is broken.

**Comment by TimothyMeadows** [comment] 2019-04-12 16:21
Interesting, this might be more of an issue with Google Recaptcha it's self. My library actually does not use jQuery at all but Google Recaptcha does.

That being said, v2-invis does take control of the button to prevent posting (this is Googles design not mine). I do have js in place that will submit this for you after Google is done. It does not depend on jQuery.

You can see the template for v2-invis here. https://github.com/TimothyMeadows/reCAPTCHA.AspNetCore/blob/master/reCAPTCHA.AspNetCore/Templates/v2Invis.tt

**Comment by TimothyMeadows** [comment] 2019-04-15 13:45
Being i can't reproduce this, i am closing this issue for now. Feel free to reopen it if you find more information that you think i can help with.

**Closed by TimothyMeadows** 2019-04-15 13:45 UTC

**Comment by Aurora7Sys** [comment] 2019-04-15 16:44
@TimothyMeadows , I have a simple project working that demonstrates the issue 100% of the time. I will zip it up and send it to your email address on your profile page here.
